server:
  port: 8769

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
mybatis:
  basepackage: com.github.wxiaoqi.security.generator.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/*.xml"


spring:
  application:
      name: ace-generator
  cloud:
    nacos:
      discovery:
        server-addr: xxx.xxx.xxx.xxx:xxxx #nacos地址、端口
  datasource:
      name: 管理后端数据库
      url: jdbc:mysql://xxx.xxx.xxx.xxx:xxxx/xxxxx?useUnicode=true&characterEncoding=UTF8 #mysql地址、端口、数据库名需要自己配置
      username: xxx #mysql用户名
      password: ******* #mysql密码
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
  sample-datasource:
      name: Sample后端数据库
      url: jdbc:mysql://xxx.xxx.xxx.xxx:xxxx/xxxxx?useUnicode=true&characterEncoding=UTF8 #mysql地址、端口、数据库名需要自己配置
      username: xxx #mysql用户名
      password: ******* #mysql密码
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
      database: 2
      host: xxx.xxx.xxx.xxx #redis地址
      port: xxxx #redis端口
      password: ****** #redis密码
      jedis:
        pool:
            max-active: 20
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true

logging:
  level:
    com.github.wxiaoqi.cloud.gate.v2: info
#    com
    org.springframework: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: heapdump,dump,threaddump,configprops,env
  security:
    enabled: false


ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ## 并发执行的最大线程数，默认10
      maxQueueSize: 1000 ## BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ## 即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

