logging:
    level:
#        tk.mybatis: DEBUG
        com.github.wxiaoqi.security.admin: DEBUG
spring:
    application:
        name: ace-admin
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    redis:
        database: 2
        host: 119.3.232.15
        port: 6379
        password: Jya3QE7M0e
        jedis:
            pool:
                max-active: 20
    servlet:
      multipart:
        # 单个文件大小
        max-file-size: 10MB
        # 设置总上传的文件大小
        max-request-size: 20MB
    datasource:
        name: test
        url: jdbc:mysql://119.3.232.15:3306/houses?useUnicode=true&characterEncoding=UTF8
        username: root
        password: Jya3QE7M0e
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    cloud:
      sentinel:
        transport:
          dashboard: 119.3.232.15:8858
      nacos:
        discovery:
          server-addr: 119.3.232.15:8848
mybatis:
    basepackage: com.github.wxiaoqi.security.admin.modules.mapper
    xmlLocation: classpath:mapper/**/*.xml
    mapper-locations: "classpath*:mapper/*.xml"

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql


server:
    port: 8762

# 必须配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 100000
  ConnectTimeout: 100000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000


# 配置swagger
swagger:
    enabled: true
    base-package: com.github.wxiaoqi.security.modules
    title: ace-admin
    version: 1.0.0.SNAPSHOT
    description: 管理后端服务
    contact:
        name: admin

#redis-cache 相关
redis:
    pool:
         maxActive: 300
         maxIdle: 100
         maxWait: 1000
    host: ${REDIS_HOST:119.3.232.15}
    port:  ${REDIS_PORT:6379}
    password: Jya3QE7M0e
    timeout: 2000
    # 服务或应用名
    sysName: cloud-admin
    enable: true
    database: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: heapdump,dump,threaddump,configprops,env
  security:
    enabled: true

# 自定义Jwt认证服务
jwt:
  token-header: Authorization
  expire: 14400
  rsa-secret: xx1WET12^%3^(WE45

wechat:
  appid: "wxba7fa72ebfba0400"
  secret: "791eef798a29484909cbebed6934fdf5"
  temp: "mX7nNrWvWYFgTj1b0gwBA_tDJS2N9lXiBILcCggwmqo"
  template: "MKSKR2tv3I3lf5wd5Eos0Cou7oYq3rzIIdbl1vdG8Gk"


#阿里云oss服务配置
aliyun:
  oss:
    bucketName: "system-town"
    endPoint: "http://oss-cn-zhangjiakou.aliyuncs.com"
    accessKeyId: "LTAI5tE9fRjdhbemYPjUfeG6"
    accessKeySecret: "qlANiedHilxp8DFSXht4yzlBYpWYpm"
    urlPrefix: "http://system-town.oss-cn-zhangjiakou.aliyuncs.com/"


# 文件路径 示例（Linux配置 /home/dangan/uploadPath）
ace:
  profile: /home/dangan/uploadPath

